/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Proj._Generator_Annotaion_Driven_All1;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
